version: '3.5'
services:
   mysql-db:
     image: mysql:latest
     # restart: always
     environment:
        MYSQL_DATABASE: 'db'
        MYSQL_USER: 'root'
        #-MYSQL_PASSWORD: 'passwd'
        MYSQL_ROOT_PASSWORD: 'passwd'
     ports:
        # <Port exposed> : < MySQL Port running inside container>
        - 3306:3306
     expose:
        - 3306
     networks:
        - backend
     volumes:
        - ./db.sql:/docker-entrypoint-initdb.d/db.sql
   java-app:
     build: .
     ports:
        - 8080:8080
     environment:
        - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db/db
        - SPRING_DATASOURCE_USERNAME=root
        - SPRING_DATASOURCE_PASSWORD=passwd
     depends_on:
        - mysql-db
     expose:
        - 8080
     networks:
        - backend
     #depends_on:
        #-db
     command: bash -c "sleep 20 && java -jar /restAPI-mysql-0.0.1-SNAPSHOT.jar"
networks:
  backend:
    driver: "bridge"
